vtk_module(vtkIOMovie
  GROUPS
    StandAlone
  TEST_DEPENDS
    vtkTestingCore
    vtkImagingCore
    vtkImagingSources
  KIT
    vtkIO
  DEPENDS
    vtkCommonExecutionModel
  PRIVATE_DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonMisc
    vtkCommonSystem
  )